### PR TITLE
Token auth

### PR DESCRIPTION
**Pull request by jgraff2**

### CODE REVIEW

**Comment by pallavi2209** [comment]
@jgraff2 Tests failing?

**Comment by jgraff2** [comment]
What if we were to make a change that breaks the authentication somehow? Without those log lines it would take longer to realize something was wrong, and would be more difficult to track down the cause.

**Comment by iamigo** [comment]
> What if we were to make a change that breaks the authentication somehow? Without those log lines it would take longer to realize something was wrong, and would be more difficult to track down the cause.

OK, I guess my main complaint is that it's a lot of noise in the logs, given that some number of authentication errors are just normal and expected part of running the service. What about just writing out err.message instead of the full err which has stack trace? Do you think we would lose too much information? We can always use debug(...) to write out the full stack trace and only turn that on when we actually want to see it?

**Comment by jgraff2** [comment]
Yeah that's a good point that it's not really an error, it's an expected part of running the service.
I was thinking of it as being similar to how we log every api request, success or not, in the main app, so we can aggregate all that data in Sumo and look for trends. But since we're not doing that at all for socket connections, we should probably only be logging errors that are truly unexpected.

So I'm thinking we should remove the error logging like you originally suggested.

**Pull request merged**
